2019-01-25 19:23:12,652 ERROR: Exception on /index [GET] [in /home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/larsle/git/microblog/app/routes.py", line 31, in index
    prev_url=prev_url)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/larsle/git/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/larsle/git/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/larsle/git/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/larsle/git/microblog/app/templates/index.html", line 14, in block "app_content"
    {% include "_post.html" %}
  File "/home/larsle/git/microblog/app/templates/_post.html", line 3, in top-level template code
    <td width="70px"><a href="{{ url_for('user', username=post.author.username) }}">
  File "/home/larsle/anaconda3/envs/microblog/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'username' is undefined
2019-01-25 19:23:21,937 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:50]
2019-01-25 19:27:41,402 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:50]
2019-01-25 19:42:43,993 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:52]
2019-01-25 19:51:56,195 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:52]
2019-01-25 19:58:27,205 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:52]
2019-01-25 20:02:56,238 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:52]
2019-01-25 20:04:54,532 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:52]
2019-01-25 20:06:28,539 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:52]
2019-01-25 20:06:48,490 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:52]
2019-01-27 10:54:42,309 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:55]
2019-01-27 11:05:14,779 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:55]
2019-01-27 14:32:59,850 INFO: Microblog startup [in /home/larsle/git/microblog/app/__init__.py:55]
